### ISSUE TITLE
[実装]分割し、ランダムの範囲を狭くする。

### ISSUE THREAD

**Issue by yukifujimoto** [yukifujimoto/stamp#10]
実装方針
①targetfeildを分割
②分割したエリア内に一個でも黒いセルが存在した場合、計算箇所の候補にする

**Comment by igarashi339** [comment]
分割する部分は実装完了。（レビュ待ち）
実行する部分を実装しプルリクを出す。

**Comment by yukifujimoto** [comment]
実行する部分を実装し、プルリクしました。

**Comment by igarashi339** [comment]
こちらのプルリクにて実装がmasterにマージされたため本チケットをクローズとする。
https://github.com/yukifujimoto/stamp/pull/21
