### ISSUE TITLE
[調査]コマンドプロンプトから実行する方法

### ISSUE THREAD

**Issue by yukifujimoto** [yukifujimoto/stamp#8]
コマンドプロンプトからexec.pyファイルを実行する方法を調査する。

**Comment by igarashi339** [comment]
大方の解決方針が判明。`sys.path` に`../` を追加すればよい。
ただし、上記の対応をとってコマンドラインからexecを実行した場合エラーが発生する。
これはおそらく `IO#input_problem()` の実装に起因する問題である。
exec-on-cli ブランチにて修正中。
https://github.com/yukifujimoto/stamp/tree/exec-on-cli

**Comment by igarashi339** [comment]
問題解決方法は判明。
プルリクを出す。

**Comment by igarashi339** [comment]
プルリクを発行した。マージされ次第クローズとする。
https://github.com/yukifujimoto/stamp/pull/17
